#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

k=1

while [ $k -le 10 ]
do
	echo "Best School"
	if [ $k -eq 9 ]; then
		echo "Hi"
	fi
	((k++))
done
