#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements

#backup the original /etc/hosts file
cp /etc/hosts ~/hosts.new

#configures an Ubuntu server "localhost" & "facebook.com"
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

#copy the new configures to the original /etc/hosts file
cp -f ~/hosts.new /etc/hosts
